using UnityEngine;
using System.Collections;

public class LanguageDescriptionScript : MonoBehaviour {
	private static string descriptionENG="Automatic coordination of the octaves is based on tuning and harmonizing of consciousness and it causes: peace, relax and harmony, it tunes and clears the states of unrest and doubts as well as remains of fears and other causes of unrest inside their core.\rThe rules of these riddles are the following: player has to guess and write down answers for 12 questions in general (full payed version). The way it gets done is that the player will get to know the answers without any help. It’s also about patience.\rIt is possible to cancel this game-quiz and if you wish to continue where you have left, you need to save the game with the “SAVE” button before ending it. If you just push the “EXIT” button, the game will not save.\rThe game-quiz does not require internet connection.\rI wish you godly patience and believe that this game-quiz will help you get rid of what you don’t need anymore. After all you will see that for yourself once you’ve finished the game-quiz without any help.\rIf you feel any better, recommend it to your friends.\rIt is required to drink clear water during the game-quiz (it’s part of the process that goes on inside of you. Processes that go on inside of you are cleansing.)\rThe things that caused you unrest and disharmony as well as things I mention above melt when you look at the pictures that will appear during playing of this game-quiz.\rI wish you a beautiful life in love.\rThe author.\r";
	private static string descriptionIT="Coordinamento automatico degli Ottava é basato sulla sintonizzazione e l´armonizzazione della coscienza e di conseguenza causa: la calma, la tranquilitá e l´armonia., sintonizza – pulisce le sensazioni di inquitudine e preoccupazioni come le rimanenze delle paure e le altre cause che creano la inquitudine e le tensioni  all´ interno. \r\rLe regole di questi indovinelli – giochi – quiz sono le seguenti. Il giocatore deve indovinare e scrivere le risposte per un totale di 12 domande (in versione completa valida) in modo che da solo arriva a\u00a0riconoscere le risposte senza gli indizi. É neccessario avere la pazienza.\rQuesto gioco-quiz é posibile interrompere e se si desidera continuare da dove il gioco sia stato  interrotto é neccessario memorizzare il gioco tramite il tasto “SAVE“ prima di chiudere il gioco. Se invece viene inserito solo „EXIT“ il gioco non viene memorizzato. \rDurante il gioco-quiz non é neccessario essere collegati su\u00a0internet. \rVi auguro la pazienza di Dio e fidatevi che questo gioco-quiz vi aiuta a liberarsi di quello che per voi non é piú utile, non vi serve piú. Alla fine lo sentirete da soli dopo aver riuscito superare il gioco con successo se giocherete da soli senza gli aiuti. \rSe dopo vi sentite meglio consigliatelo ai vostri amici, alle persone a\u00a0voi care. \rDurante il gioco-quiz é neccessario bere l´acqua pura (fa parte del processo che sta succedendo dentro di voi. I\u00a0processi che stanno succedendo dentro di voi sono purificativi.)\rQuello che vi causava inquietudine e disarmonia e anche quello che ho descritto sopra si scioglie perché guardate anche i\u00a0deisegni che si visualizzano durante il gioco-quiz.\rVi auguro una bellissma vita in amore.\rL´autore.\r";
	private static string descriptionESP="La coordinación de Octavas está basada en  la conciencia modulada y armonizada  y ocasiona: calma, tranquilidad y armonía, sintoniza-limpia el estado de inquietud y miedos, como también restos de miedos y otros motivos que causan inquietud y ansiedad en su interior.\rLas reglas de estas adivinanzas-juego-encuesta son las siguientes. El  jugador  tiene que adivinar y escribir las respuestas de 12 preguntas (usando la versión entera-válida) y eso de tal forma que él mismo encuentre la respuesta sin otros recursos. Hay que tener paciencia.\rEste juego-encuesta es posible interrumpirlo, y si desea continuar en el mismo lugar donde  ha terminado hay que presionar la tecla “SAVE-GUARDAR“ . En el caso de que presione solo “EXIT-SALIDA“ el juego no se guarda.\rDurante el juego-encuesta no es necesario estar conectado al Internet.\rLes deseo a\u00a0ustedes la  Eterna paciencia y confíen en mí que este juego-encuesta los ayudará a\u00a0liberarse de todo lo que ya no les sirve. Por fin lo van a\u00a0notar en ustedes mismos al finalizar con éxito este juego-encuesta.\rSi se encuentran mejor, recomienden este juego-encuesta a\u00a0sus  familiares y amigos.\rDurante el juego es importante beber agua sin gas o sin azucar (porque eso también  forma parte de este proceso que transcurre en su interior. Los procesos son purificantes.)\rLo que  provocaba en ustedes  inquietud y disarmonía, como también lo que he mencionado arriba de este artículo, se disuelve con observar también los dibujos que aparecerán durante este juego-encuesta.\rLes deseo una vida llena de amor.\rAutor.\r";
	private static string descriptionPT="Coordenação Octave é baseada na consciência modulada correo electrónico harmonizada Provoca:\r\n Calma, tranquilidade e harmonia, estado de puesta a punto de Limpa Ansiedade e medos, bem Como restos de medos e outras Razões Que Causam preocupação e Ansiedade em seu interior.Como regras destes adivinhando-juego-pesquisa são os seguintes: O jogador tem que adivinhar e escrever como Respostas de 12 Perguntas (Usando un versão completa -valida  ) e Que, Para Que ele ENCONTRAR como  Respostas, SEM outros Recursos. Temos de ter paciência . Este jogo-inquérito de interferir possível e se deseja continuar sin mesmo Lugar onde ele Terminar, você tem que pressionar una Tecla \"SAVE-SAVE\". Se você pressionar somente \"EXIT-SALIDA\" O Jogo não Será Salvo. Durante O Jogo não é preciso Navegar pela internet. Desejo pra os Jogadores ter eterna paciência  e Confiar em mim ya Que this jogo-pesquisa ajuda a se livrar de tudo o que não mais lhe sirven. Finalmente eles vão perceber em si mesmo párrafo Completar com sucesso Este jogo-inquérito.Se eles são melhores, lo recomiendo jogo-encuesta sua família e amigos.Durante jogo é Importante para beber água sem gás Açúcar ou  (isso  também faz parte deste processo Que ocorre de Dentro. Os processos de são Purificação.)O que causou inquietação e desarmonía em você, já Como acima mencionado deste artigo, também se disuelva ver os desenhos Que aparecem Durante jogo-inquérito.Desejo-lhe uma vida cheia de amor.\r\nAutor.\r\n";
	private static string descriptionRU="Автоматическая Координация Октавы основывается на настройке и сочетании сознаний и дает покой,спокойствие и гармонию, настраивает - очищает состаяние тревоги и беспокойства, а также остатки страха и других причин, вызывающих беспокойство и волнение внутри .\r\n\r\nПравила этой головоломки–игры-викторины есть следующие. Игрок должен угадать и написать ответы на 12 вопросов (в полной - платной версии) и он приходит к познанию самостаятельно, без пособий. Это тоже о терпении.\r\n\r\nЭту игру-викторину тоже можно прервать, и если хотите продолжать, где Вы остановились, необходимо сохранить ее с помощью кнопки \"сохранить\" перед выходом. Если Вы вводите просто \"выход\" так все это без сохранения игры.\r\n\r\nВ ходе игры-викторины Вы не должны быть подключены к интернету.\r\n\r\nЖелаю Вам Божьего терпения, и поверьте тот факт, что данная игра-викторина поможет Вам избавиться от того, что уже является для Вас излишним. Наконец, после его успешного завершения Вы это будете чувствовать, если будете играть самостоятельно и без пособий.\r\n\r\nЕсли Вы чувствуете себя лучше, рекомендуйте это своим близким и друзьям.\r\n\r\nВ ходе игры-викторины необходимо пить чистую воду (она является частью процесса, который в организме проходит. Эти происходящие процессы очистные)\r\n\r\nВсе, что Вам вызывало волнение и дисгармонию, а также то, что я включил выше, растворяется даже через образы, которые Вы во время этой игры-викторины рассматриваете.\r\n\r\nЖелаю Вам замечательной жизни в любви.\r\n\r\nАвтор.\r\n";
	//Error
	private static string errorENG = "Error";

	public static string GetDescription() {
		switch (EnumLanguagesScript.GetLanguage ()) {
		case EnumLanguagesScript.Language.ENG:
			return descriptionENG;
		case EnumLanguagesScript.Language.IT:
			return descriptionIT;
		case EnumLanguagesScript.Language.ESP:
			return descriptionESP;
		case EnumLanguagesScript.Language.PT:
			return descriptionPT;
		case EnumLanguagesScript.Language.RU:
			return descriptionRU;
		default :
			return errorENG;
		}
	}
}